properties(
    [
        parameters(
             [
                        string(name: 'Bucket_Name', defaultValue: 'ravijenkins'),
                    string(name: 'Bucket_Name2', defaultValue: 'ravikanthjenkins')
             ]
        )
    ]
)
pipeline {
    agent {
        docker {
            image 'devopscafe/maven-awscli'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
            post {
                success  {
                    emailext  (
                to: "rapoluravikanth@gmail.com",
                subject: "Job was Successful: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """=== Job Details as Below === 
                  Job Name = '${env.JOB_NAME}'
                  Job Build Number = '${env.BUILD_NUMBER}'
                  Build Info @ '${env.BUILD_URL}' 
                  """
            )
                }
                failure  {
                    emailext  (
                to: "rapoluravikanth@gmail.com",
                subject: "Job Failed: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """=== Job Details as Below === 
                  Job Name = '${env.JOB_NAME}'
                  Job Build Number = '${env.BUILD_NUMBER}'
                  Build Info @ '${env.BUILD_URL}' 
                  """
            )
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Store-in-S3 bucket1') {
            steps {
                sh "aws s3 cp /var/lib/jenkins/workspace/btree/target/my-app-1.0-SNAPSHOT.jar s3://${params.Bucket_Name}/"
            }
        }
    stage('Store-in-S3 bucket2') {
            steps {
                sh "aws s3 cp /var/lib/jenkins/workspace/btree/target/my-app-1.0-SNAPSHOT.jar s3://${params.Bucket_Name2}/"
            }
        }
}
}
